"""
Django settings for WebGoGreen project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 🔥 Thêm dòng này nếu chưa có

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7!_knwvm=m-ehd@4_7_9%&^$5s9pva=6z$k34oi_1g^#ijf15j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "localtest.me"]



# Application definition

INSTALLED_APPS = [
    "jazzmin",

    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 🌍 Allauth (Google Login)
    'django.contrib.sites',   # BẮT BUỘC
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Ứng dụng của bạn
    'app',

    # Cron
    'django_crontab',
]

# BẮT BUỘC CHO ALLAUTH
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}
SOCIALACCOUNT_LOGIN_ON_GET = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # ⭐ BẮT BUỘC THÊM Ở ĐÂY
    'allauth.account.middleware.AccountMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'WebGoGreen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "app" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WebGoGreen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xxxxxxup',
        'USER': 'root',
        'PASSWORD': '1xxxxx',  # đổi theo mật khẩu MySQL của bạn
        'HOST': '127.0.0.1',
        'PORT': 'xxxxxx',
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "app" / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'app.User'
USE_TZ = False
TIME_ZONE = 'Asia/Ho_Chi_Minh'
LOGIN_URL = '/accounts/login/'
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# ===============================
# ✉️ CẤU HÌNH GỬI EMAIL NHẮC SỰ KIỆN
# ===============================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'          # hoặc dùng SendGrid / Mailgun
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'xxxxxx'        # 🔸 Thay bằng email của bạn
EMAIL_HOST_PASSWORD = 'xxxxxxx'   # 🔸 Mật khẩu ứng dụng (App Password)
DEFAULT_FROM_EMAIL = 'Go Green Clean Up 🌱 <xxxxxx'

# ===============================
# 🕐 TỰ ĐỘNG GỬI NHẮC SỰ KIỆN MỖI NGÀY
# ===============================
CRONJOBS = [
    ('0 7 * * *', 'app.cron.send_event_reminders'),  # chạy mỗi sáng 7h
]


JAZZMIN_SETTINGS = {
    "site_title": "Quản trị Web Go Green",
    "site_header": "Web Go Green Admin",
    "site_brand": "Trang quản trị",
    "welcome_sign": "Chào mừng bạn quay lại!",
    "copyright": "© Web Go Green",

    "site_logo": "images/logo.png",
    "login_logo": "images/logo.png",
    "site_icon": "images/favicon.png",

    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "navigation_expanded": True,
    "show_ui_builder": False,

    # ==========================
    # 🔥 Quan trọng để dùng menu tùy chỉnh
    # ==========================
    "custom_side_menu": True,
    "custom_css": "css/home.css",


    # ==========================
    # 📌 SIDEBAR GOM NHÓM – CHUẨN TỪNG MODEL
    # ==========================
    "side_menu": {
        "items": [

            # ===== NHÓM 1: SỰ KIỆN =====
            {
                "label": "Quản lý sự kiện",
                "icon": "fas fa-calendar-check",
                "models": [
                    "app.event",
                    "app.eventimage",
                    "app.eventparticipation",
                    "app.eventcomment",
                    "app.checkin",
                ],
            },

            # ===== NHÓM 2: NGƯỜI DÙNG =====
            {
                "label": "Người dùng & Tình nguyện viên",
                "icon": "fas fa-users",
                "models": [
                    "app.user",
                    "app.profile",
                    "app.userbadge",
                    "app.participationcertificate",
                ],
            },

            # ===== NHÓM 3: MẠNG XÃ HỘI =====
            {
                "label": "Mạng xã hội",
                "icon": "fas fa-hashtag",
                "models": [
                    "app.post",
                    "app.likepost",
                    "app.followers",
                    "app.comment",
                ],
            },

            # ===== NHÓM 4: ĐIỂM & QUÀ TẶNG =====
            {
                "label": "Điểm thưởng & Quà",
                "icon": "fas fa-gift",
                "models": [
                    "app.reward",
                    "app.rewardredeem",
                    "app.score",
                ],
            },

            # ===== NHÓM 5: GỢI Ý RÁC & AI =====
            {
                "label": "Rác & AI",
                "icon": "fas fa-recycle",
                "models": [
                    "app.report",
                    "app.trashcategory",
                ],
            },

            # ===== NHÓM 6: HỆ THỐNG =====
            {
                "label": "Hệ thống",
                "icon": "fas fa-cogs",
                "models": [
                    "app.notification",
                    "app.activitylog",
                    "app.message",
                ],
            },
        ]
    },

    # ==========================
    # ICON ĐẸP
    # ==========================
    "icons": {
        "app.user": "fas fa-user",
        "app.profile": "fas fa-id-card",
        "app.userbadge": "fas fa-award",
        "app.participationcertificate": "fas fa-certificate",

        "app.event": "fas fa-calendar-check",
        "app.eventparticipation": "fas fa-user-check",
        "app.eventimage": "fas fa-image",
        "app.checkin": "fas fa-qrcode",
        "app.eventcomment": "far fa-comment",

        "app.post": "fas fa-pencil-alt",
        "app.likepost": "fas fa-heart",
        "app.followers": "fas fa-user-friends",
        "app.comment": "fas fa-comments",

        "app.reward": "fas fa-gift",
        "app.rewardredeem": "fas fa-box-open",

        "app.report": "fas fa-map-marker-alt",
        "app.trashcategory": "fas fa-recycle",

        "app.notification": "fas fa-bell",
        "app.activitylog": "fas fa-history",
        "app.message": "fas fa-paper-plane",
    },
}

OPENAI_API_KEY = "sk-xxxxx"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        "SCOPE": ["email", "profile"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"
SOCIALACCOUNT_ADAPTER = "allauth.socialaccount.adapter.DefaultSocialAccountAdapter"
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
